### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by jkingslake** [r-barnes/Barnes2020-FillSpillMerge#21] opened 2024-01-16 01:57 UTC
Hi, this looks like a fantastic tool and I am looking forward to trying it out!

I am trying to compile followinghte instructions in README.md and getting the following errors:
```
cmake -D CMAKE_C_COMPILER="/usr/bin/clang" -D CMAKE_CXX_COMPILER="/usr/bin/clang++" -DUSE_GDAL=ON -DCMAKE_BUILD_TYPE=Release ..

make
```
gives
```
[  5%] Building CXX object submodules/dephier/submodules/richdem/CMakeFiles/richdem.dir/src/richdem.cpp.o
[ 11%] Building CXX object submodules/dephier/submodules/richdem/CMakeFiles/richdem.dir/src/random.cpp.o
[ 17%] Building CXX object submodules/dephier/submodules/richdem/CMakeFiles/richdem.dir/src/gdal.cpp.o
[ 23%] Building CXX object submodules/dephier/submodules/richdem/CMakeFiles/richdem.dir/src/terrain_generation/terrain_generation.cpp.o
[ 29%] Building CXX object submodules/dephier/submodules/richdem/CMakeFiles/richdem.dir/src/terrain_generation/PerlinNoise.cpp.o
[ 35%] Linking CXX static library librichdem.a
[ 35%] Built target richdem
[ 41%] Building CXX object CMakeFiles/fsm_paper_tests.exe.dir/paper/fsm_paper_tests.cpp.o

In file included from /Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/paper/fsm_paper_tests.cpp:3:
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/include/fsm/fill_spill_merge.hpp:1029:17: error: cannot assign to variable 'water_vol' with const-qualified type 'const double'
      water_vol = current_dep_volume;
      ~~~~~~~~~ ^
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/include/fsm/fill_spill_merge.hpp:871:26: note: in instantiation of function template specialization 'richdem::dephier::DetermineWaterLevel<float>' requested here
      auto water_level = DetermineWaterLevel(wtd(c.x,c.y), water_vol, topo(c.x,c.y), cells_affected.size(), total_elevation);
                         ^
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/include/fsm/fill_spill_merge.hpp:721:5: note: in instantiation of function template specialization 'richdem::dephier::FillDepressions<float, float>' requested here
    FillDepressions(
    ^
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/include/fsm/fill_spill_merge.hpp:196:3: note: in instantiation of function template specialization 'richdem::dephier::FindDepressionsToFill<float, float>' requested here
  FindDepressionsToFill(OCEAN, deps, topo, label, wtd);
  ^
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/paper/fsm_paper_tests.cpp:63:7: note: in instantiation of function template specialization 'richdem::dephier::FillSpillMerge<float, float>' requested here
  dh::FillSpillMerge(topo, label, flowdirs, deps, wtd);
      ^
/Users/jkingslake/Documents/science/BFRN_meltwater/Barnes2020-FillSpillMerge/include/fsm/fill_spill_merge.hpp:108:16: note: variable 'water_vol' declared const here
  const double water_vol,
  ~~~~~~~~~~~~~^~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/fsm_paper_tests.exe.dir/paper/fsm_paper_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/fsm_paper_tests.exe.dir/all] Error 2
make: *** [all] Error 2
```

Any help would be much appreciated.

**Comment by jkingslake** [comment] 2024-01-16 02:03
p.s. the clang version is:
```
% clang --version                                                                                                                
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by r-barnes** [comment] 2024-01-16 03:26
Looking.

**Comment by r-barnes** [comment] 2024-01-16 03:37
@jkingslake - I encountered problems with doctest while compiling and upgraded it to fix those.

I was unable to reproduce your issues and don't see how it could arise from the current master. Could you please try again with a fresh build and manually check if the variable in question is `const`?

**Comment by r-barnes** [comment] 2024-01-16 03:38
nm: Let me take another look a this...

**Comment by r-barnes** [comment] 2024-01-16 03:40
@jkingslake - I was able to see the problem and have just pushed a fix for it. This was a fairly easy one and I think you could have put up a PR fixing it. Thanks for reaching out!

**Closed as completed by r-barnes** 2024-01-16 03:40 UTC

**Comment by jkingslake** [comment] 2024-01-16 19:50
thank you! This is working for me now!
